language: node_js
node_js:
  - "6.11.5"
install:
  - rvm install 2.4.0
  - gem install jekyll
  - gem install jekyll-tidy
before_script:
  - yarn install
script: yarn build
cache:
  yarn: true
  bundler: true
  directories:
  - node_modules
  - /home/travis/.rvm/
deploy:
  provider: pages
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  verbose: true
  local_dir: _site
  on:
    branch: master