title: Jekyll Webpack Starter
description: >-
  A simple Jekyll + Webpack starter

url: ""
baseurl: ""

markdown: kramdown
permalink: /:title

compiledPath: dist

include: ["_pages"]

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - webpack*
  - yarn*
  - .babelrc
  - .browserslistrc
  - readme.md
  - CNAME
  - package.json
  - postcss.config.js

plugins:
  - jekyll-feed