title: Jekyll Webpack Starter
description: >-
  A simple Jekyll + Webpack starter

#domain
url: "" 
baseurl: ""
runmode: prod

markdown: kramdown
permalink: /:title

compiled_path: dist

ga_trackingid: UA-139006851-1

plugins:
  - jekyll-tidy

jekyll_tidy:
  compress_html: false

include: ["_pages"]

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - webpack*
  - yarn*
  - .babelrc
  - .browserslistrc
  - readme.md
  - CNAME
  - package.json
  - postcss.config.js